stages:
  import-musicbrainz:
    cmd: python ingest.py --musicbrainz
    deps:
    - sql/mb_artist.sql
    - sql/mb_recording.sql
    - source/musicbrainz/artist.tar.xz
    - source/musicbrainz/recording.tar.xz
    outs:
    - data/musicbrainz.db

  import-mlhd:
    cmd: python ingest.py --mlhd
    deps:
    - source/mlhdplus
    outs:
    - data/mlhd
  
  generate_stats:
    cmd: python datanalysis/analysis.py
    deps:
      - datanalysis/analysis.py
      - data/musicbrainz.db
      - data/mlhd/
    outs:
      - datanalysis/outputs/