stages:
  import-musicbrainz:
    cmd: python ingest.py --musicbrainz
    deps:
    - sql/mb_artist.sql
    - sql/mb_recording.sql
    - source/musicbrainz/artist.tar.xz
    - source/musicbrainz/recording.tar.xz
    outs:
    - data/musicbrainz.db

  import-mlhd:
    cmd: python ingest.py --mlhd --use-mapping
    deps:
    - source/mlhdplus
    - musicdata/mlhd.py
    - musicdata/layout.py
    - musicdata/params.py
    outs:
    - data/mlhd
    - data/mlhd_ids.parquet

  prep-mlhd:
    cmd: python prep.py
    deps:
    - data/mlhd/
    - data/musicbrainz.db
    - data/mlhd_ids.parquet
    - musicdata/mlhd_prep.py
    - musicdata/layout.py
    outs:
    - data/mlhdv2.parquet

  # generate_stats:
  #   cmd: python datanalysis/summarizestats.py
  #   deps:
  #     - datanalysis/summarizestats.py
  #     - data/musicbrainz.db
  #     - data/mlhd/
  #   outs:
  #     - datanalysis/outputs/

