name: musicdata
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pyarrow>=14
  - pyarrow-stubs
  - zstd
  - zstandard
  - dvc=3
  - dvc-s3
  - dvc-webdav
  - pyyaml
  - libarchive=3
  - python-duckdb=0.10
  - duckdb-cli=0.10
  - enlighten~=1.12
  - pyzmq==26.*
  - humanize
  - pip:
    - docopt-ng>=0.9
    - sandal>=0.1.0a4
    - progress-api>=0.1.0a4
    - manylog>=0.1.0a3
    - pyarrow-stubs>=10.0
platforms:
- linux-64
- osx-arm64
