name: musicdata
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pyarrow>=14
  - zstd
  - zstandard
  - dvc=3
  - dvc-s3
  - dvc-webdav
  - python-duckdb=0.10
  - duckdb-cli=0.10
  - enlighten~=1.12
  - pip:
    - docopt-ng>=0.9
    - sandal>=0.1.0a2
platforms:
- linux-64
- osx-arm64
