[project]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "musicdata"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.11.0"
pyarrow = ">=14"
pyarrow-stubs = "*"
zstd = "*"
zstandard = "~=0.23.0"
dvc = "~=3.56"
dvc-s3 = "~=3.0"
dvc-webdav = "~=3.0"
dvc-azure = "~=3.0"
pyyaml = "~=6.0"
libarchive = "~=3.0"
python-duckdb = "~=1.0"
duckdb-cli = "~=1.0"
enlighten = "~=1.12"
pyzmq = "~=26.0"
humanize = "~=4.11"

[pypi-dependencies]
docopt-ng = ">=0.9"
sandal = "~=0.1.0"
progress-api = "~=0.1.0"
manylog = "~=0.1.0"
pyarrow-stubs = ">=10.0"
